source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ECDrawerLayout_Example', :exclusive => true do
  pod "ECDrawerLayout", :path => "../"
end

target 'ECDrawerLayout_Tests', :exclusive => true do
  pod "ECDrawerLayout", :path => "../"

  
end
